config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations'
               }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users,only: [:index,:show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users ,only: [:index, :show, ] do
    resources :posts, only: [:index, :create, :new, :show, :destroy] do
      resources :comments, only: [:index, :create, :destroy]
      resources :likes, only: [:index, :create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  has_many :posts, foreign_key: 'author_id', class_name: 'Post'
  has_many :likes, foreign_key: 'author_id', class_name: 'Like'
  has_many :comments, foreign_key: 'author_id', class_name: 'Comment'

  def recent_posts
    posts.last(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  #   skip_before_action :verify_authenticity_token
  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.json { render json: @user }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_bio_card.html.erb
<section>
    <div class='bio_card'>
        <h3> Bio</h3>
        <p><%= user.bio || 'No bio' %></p>
    </div>
</section>

app/views/users/_user_profile.html.erb
<section>
    <div class='user_card'>
        <img src=<%= user.photo %> class='user_image' >
        <div class="user_info">
            <h2><%= user.name %></h2>
            <p>Number of posts:<%= user.post_counter || 0 %></p>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<h1 class='users_heading'>List of all Users<h1>
<div class='all_users'>
    <% @users.each do |user| %>
        <%= link_to user_path(user.id) do %>
            <%= render partial: 'user_profile', locals: {user:user} %>
        <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<nav class="fs-6 p-3 container mt-2 p-2 bio">
  <%= link_to "Home", root_path, class:"button px-3 my-2" %>
</nav>

<h1 class='users_heading'>User Details </h1>

<%= render partial: 'user_profile', locals: {user:@user} %>
<%= render partial: 'bio_card', locals: {user:@user} %>

<div class='recent_posts'>
    <% @user.recent_posts.each do |post| %>
        <div class='post_card'>
            <%= link_to user_post_path(@user.id, post.id), id: "user_post#{post.id}" do %>
                <h3>Post: <%= post.title %></h3>
                <p><%= post.text.truncate(30) %></p>
            <% end %>
            <div class='interactions'>
                <span>Comments: <%= post.comments.size || 0 %></span>
                <span>Likes: <%= post.likes.size || 0 %></span>
            </div>
        </div>
    <% end %>
</div>
<div class='all_posts'>
<button class='d-flex justify-content-center'>
<%= link_to "See all posts" , user_posts_path(@user) %>
</button>

</div>