config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
               path: '',
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 registration: 'signup'
               },
               controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations'
               }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :users,only: [:index,:show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users ,only: [:index, :show, ] do
    resources :posts, only: [:index, :create, :new, :show, :destroy] do
      resources :comments, only: [:index, :create, :destroy]
      resources :likes, only: [:index, :create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # validates :title, presence: true, length: { maximum: 250 }
  # validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :likes, foreign_key: 'post_id', class_name: 'Like', dependent: :destroy
  has_many :comments, foreign_key: 'post_id', class_name: 'Comment', dependent: :destroy

  belongs_to :author, class_name: 'User', counter_cache: 'post_counter'

  after_create :update_post_counter

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end

  def recent_comments
    comments.last(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  #   skip_before_action :verify_authenticity_token
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    respond_to do |format|
      format.json { render json: @posts }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    respond_to do |format|
      format.json { render json: @post }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index; end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    new_post = current_user.posts.build(post_params)

    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to user_post_path(new_post.author_id, new_post.id), notice: 'Post created successfully'
        else
          render :new, alert: 'An error occured. Please try again!'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user), notice: "Successfully deleted the post #{@post.title}."
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="home d-flex mx-5 justify-content-between my-3">
<%= link_to "Home", root_path, class: "button px-3" %>
<%= link_to "Back", :back, class: "button px-3" %>
</div>


<h1 class="users_heading"> List of Posts from the User</h1>

<%= render partial: 'users/user_profile', locals: {user: current_user} %>
<button class="button d-flex justify-content-center">
    <%= link_to "Create new post", new_user_post_path(current_user.id) %>
</button>

<% current_user.posts.each do |post| %>
    <div class='post_card'>
        <div class="post-details">
        <%= link_to user_post_path(current_user.id, post.id), id: "user_post#{post.id}" do %>
            <h3><%= post.title %></h3>
            <p><%= post.text.truncate(30) %></p>
        <% end %>
        </div>
        <div class='interactions'>
            <span>Comments: <%= post.comments_counter || 0 %></span>
            <span>Likes: <%= post.likes_counter || 0 %></span>
        </div>
    </div>

        <div class="post_card post_comments">
            <% post.recent_comments.each do |comment| %>
                <div class='comment-card'>
                    <%= comment.author.name %> : <%= comment.text %>
                </div>
            <% end %>
        </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="users_heading"> Create new post</h1>

<section class="fs-4 p-3 container mt-5 p-2">
  <%= form_with model: @post, url: user_posts_path, method: :post do |f| %>
    <%= f.label :title, "Title", class: "form-label fs-6" %>
    <%= f.text_field :title, :placeholder => "Title goe here...", required: true, class: "form-control mb-4" %>
    <%= f.label :text, "Write a new post", class: "form-label fs-6" %>
    <%= f.text_area :text, size: "80x15", :placeholder => "Add your post here...", required: true, class: "form-control" %>
    <%= f.submit "Add Post", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<div>
    <nav class="fs-6 p-3 container mt-2 p-2 bio">
      <%= link_to "Home", root_path, class: "button px-3" %>
    </nav>
    <h1 class='users_heading'>Post Details</h1>
   <div class='post_card'>
    <div class=' d-flex justify-content-between'>
        <h4><%= @post.title %> by <%= link_to user_path(@post.author.id) do %> <%= @post.author.name %> <% end %></h4>
        <p>Comments : <%= @post.comments_counter || 0 %> Likes : <%= @post.likes.size || 0 %> </p>
    </div>
        <%= @post.text %>
    </div>

    <div class='post_card'>
        <% @post.comments.each do |c| %>
            <div class='comment-card'>
                    <%= c.author.name %> : <%= c.text %>
                </div>
                <% if can? :destroy, c %>
          <%= button_to "Delete Comment", user_post_comment_path(@post.author.id,@post.id, c.id ), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>)),

        <% end %>
      <% end %>
    </div>
    <% if can? :destroy, @post %>
            <%= button_to "Delete Post", user_post_path(@post.author.id,@post.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    <% end %>


    <%= render partial: "likes/create" %>
    <%= render partial: 'comments/create' %>

</div>